### ISSUE TITLE
Hacktoberfest: Dog search demo update

### ISSUE THREAD

**Issue by iamleonie** [weaviate-tutorials/DEMO-image-search-dogs#1]
This is the tracker for polishing the “Dog image search” demo. Please refer to our [Hacktoberfest 2023 blog](https://weaviate.io/blog/hacktoberfest-2023) if you want to contribute! 

List of items to contribute:

- [x]  Run the existing demo and identify and document what exists and what is or isn’t working for the next task
- [x]  Fixes for any of the identified issues 
    - [x] python flask-app/application.py fails to run with error ImportError: cannot import name 'url_quote' from 'werkzeug.urls'
    - [x] Re-add missing query.py file from [here](https://github.com/weaviate/weaviate-examples/commit/61627396e3cc8b9d8d77034795983af1364484f7) and test if it still works. (claimed by @lalit-k )
- [ ]  Update README to include:
    - [x] Short description
    - [x] used technology
        - [x] used Weaviate modules/ML models
    - [ ] demo video or screenshots of demo usage
    - [x] Prerequisites
    - [x] Setup instructions
    - [x] Usage instructions
    - [x] Dataset license if applicable
    - [x] Review [blog post](https://weaviate.io/blog/how-to-build-an-image-search-application-with-weaviate) to improve README (claimed by @AryanSankholkar )
- [ ] Possible improvements/enhancements
    - [ ] Replace current sample data with a larger dataset (e.g., from Kaggle)
    - [ ] Add progress bar to import file
    - [ ] Prettify frontend
    - [ ] Include query.py into frontend
    - [ ] Extend existing tests (e.g., see our [example](https://github.com/databyjp/distyll) for a starting point)
    - [x] Conversion to new [Weaviate Python client](https://weaviate.io/blog/collections-python-client-preview)
        - [ ] After Weaviate release 1.22: swap out preview image

**We're open to further suggestions. If you have any further potential improvement ideas, let us know in the comments!**

📣You can contribute parts of the issue or the whole issue. Please comment below to volunteer for the part(s) you want to contribute to.

❓For any questions you might have along the way, join our [Discourse community forum](https://forum.weaviate.io/t/welcome-to-hacktoberfest-2023/764), where we're ready to answer your questions. Or join our dedicated #hacktoberfest channel in our [Weaviate Community Slack](https://weaviate.slack.com/) channel to stay connected and receive real-time support.

✅For your PR, please mention this issue and set @iamleonie as the reviewer and we will review your PR shortly.

**Comment by lalit-k** [comment]
@iamleonie I ran this demo and observed following 2 issues.

1. `python flask-app/application.py` fails to run with error `ImportError: cannot import name 'url_quote' from 'werkzeug.urls'`
2. query.py mentioned here in steps https://github.com/weaviate-tutorials/DEMO-image-search-dogs#run-the-query is missing from repo. 

Working on fixing 1st issue now.

Can take care of 2nd issue also later if that's intentionally not added in repo?

thanks!

**Comment by lalit-k** [comment]
@iamleonie Fixed the ImportError issue and updated the readme prerequisites too. Commit added on the same PR.

Thanks!

**Comment by lalit-k** [comment]
@iamleonie I'm looking into conversion to new Weaviate python client. thanks!

**Comment by iamleonie** [comment]
> I ran this demo and observed following 2 issues.
> 
> 1. `python flask-app/application.py` fails to run with error `ImportError: cannot import name 'url_quote' from 'werkzeug.urls'`
> 2. query.py mentioned here in steps https://github.com/weaviate-tutorials/DEMO-image-search-dogs#run-the-query is missing from repo.
> 
> Can take care of 2nd issue also later if that's intentionally not added in repo?

@lalit-k I had a look at the [original repo](https://github.com/weaviate/weaviate-examples/tree/main/nearest-neighbor-dog-search) for this demo, and couldn't find the query.py either. I am assuming the file was never added. 

@erika-cardenas Do you by chance, know anything about the history of the "query.py" file or its contents?

**Comment by erika-shorten** [comment]
Hi @lalit-k,
Thanks for raising the issue! From memory, I think the `query.py` file had a simple query to find dogs weighing less than 60 pounds. That file isn't needed for the demo.

**Comment by lalit-k** [comment]
Hi @iamleonie Converted the code to new Weaviate Python Client and raised PR. thank you!

**Comment by aaalexlit** [comment]
> Hi @lalit-k, Thanks for raising the issue! From memory, I think the `query.py` file had a simple query to find dogs weighing less than 60 pounds. That file isn't needed for the demo.

as far as I can see, it was removed with the deletion of the `weight` property
https://github.com/weaviate/weaviate-examples/commit/61627396e3cc8b9d8d77034795983af1364484f7

**Comment by iamleonie** [comment]
Thanks @aaalexlit for the find. I will add it as a possible contribution to re-add the file and test if it still works.

**Comment by lalit-k** [comment]
thanks @aaalexlit for looking into it.

@iamleonie  raised a PR and added the query.py back.

**Comment by AryanSankholkar** [comment]
@iamleonie Hi, this would be my first contribution.

Can I work on this "Review blog to improve README"

**Comment by AryanSankholkar** [comment]
@iamleonie 

i have completed the task and created a pull request.Can you please take a look?

**Comment by iamleonie** [comment]
Thank you, everyone, for contributing to a successful Hacktoberfest 2023!

This issue will now be closed.

If you are still working on any topics, you can, of course, continue on them. However, please note that any PRs created after Oct 31st will not count towards Hacktoberfest.
